// https://www.w3schools.com/tags/default.asp
export const a = ({children, ...rest}) => <a {...rest}>{children}</a>
export const abbr = ({...rest}) => <abbr {...rest} />
export const acronym = ({...rest}) => <acronym {...rest} />
export const address = ({...rest}) => <address {...rest} />
export const applet = ({...rest}) => <applet {...rest} />
// export const area = ({...rest}) => <area {...rest} />
export const article = ({...rest}) => <article {...rest} />
export const aside = ({...rest}) => <aside {...rest} />
export const audio = ({...rest}) => <audio {...rest} />
export const b = ({...rest}) => <b {...rest} />
export const base = ({...rest}) => <base {...rest} />
export const basefont = ({...rest}) => <basefont {...rest} />
export const bdi = ({...rest}) => <bdi {...rest} />
export const bdo = ({...rest}) => <bdo {...rest} />
export const big = ({...rest}) => <big {...rest} />
export const blockquote = ({...rest}) => <blockquote {...rest} />
export const body = ({...rest}) => <body {...rest} />
export const br = ({...rest}) => <br {...rest} />
export const button = ({...rest}) => <button {...rest} />
export const canvas = ({...rest}) => <canvas {...rest} />
export const caption = ({...rest}) => <caption {...rest} />
export const center = ({...rest}) => <center {...rest} />
export const cite = ({...rest}) => <cite {...rest} />
export const code = ({...rest}) => <code {...rest} />
export const col = ({...rest}) => <col {...rest} />
export const colgroup = ({...rest}) => <colgroup {...rest} />
export const data = ({...rest}) => <data {...rest} />
export const datalist = ({...rest}) => <datalist {...rest} />
export const dd = ({...rest}) => <dd {...rest} />
export const del = ({...rest}) => <del {...rest} />
export const details = ({...rest}) => <details {...rest} />
export const dfn = ({...rest}) => <dfn {...rest} />
export const dialog = ({...rest}) => <dialog {...rest} />
export const dir = ({...rest}) => <dir {...rest} />
export const div = ({...rest}) => <div {...rest} />
export const dl = ({...rest}) => <dl {...rest} />
export const dt = ({...rest}) => <dt {...rest} />
export const em = ({...rest}) => <em {...rest} />
export const embed = ({...rest}) => <embed {...rest} />
export const fieldset = ({...rest}) => <fieldset {...rest} />
export const figcaption = ({...rest}) => <figcaption {...rest} />
export const figure = ({...rest}) => <figure {...rest} />
export const font = ({...rest}) => <font {...rest} />
export const footer = ({...rest}) => <footer {...rest} />
export const form = ({...rest}) => <form {...rest} />
export const frame = ({...rest}) => <frame {...rest} />
export const frameset = ({...rest}) => <frameset {...rest} />
export const h1 = ({children, ...rest}) => <h1 {...rest}>{children}</h1>
export const h2 = ({children, ...rest}) => <h2 {...rest}>{children}</h2>
export const h3 = ({children, ...rest}) => <h3 {...rest}>{children}</h3>
export const h4 = ({children, ...rest}) => <h4 {...rest}>{children}</h4>
export const h5 = ({children, ...rest}) => <h5 {...rest}>{children}</h5>
export const h6 = ({children, ...rest}) => <h6 {...rest}>{children}</h6>
export const head = ({...rest}) => <head {...rest} />
export const header = ({...rest}) => <header {...rest} />
export const hr = ({...rest}) => <hr {...rest} />
export const html = ({...rest}) => <html {...rest} />
export const i = ({...rest}) => <i {...rest} />
export const iframe = ({title, ...rest}) => <iframe title={title} {...rest} />
export const img = ({alt, ...rest}) => <img alt={alt} {...rest} />
export const input = ({...rest}) => <input {...rest} />
export const ins = ({...rest}) => <ins {...rest} />
export const kbd = ({...rest}) => <kbd {...rest} />
export const label = ({...rest}) => <label {...rest} />
export const legend = ({...rest}) => <legend {...rest} />
export const li = ({...rest}) => <li {...rest} />
export const link = ({...rest}) => <link {...rest} />
export const main = ({...rest}) => <main {...rest} />
export const map = ({...rest}) => <map {...rest} />
export const mark = ({...rest}) => <mark {...rest} />
export const meta = ({...rest}) => <meta {...rest} />
export const meter = ({...rest}) => <meter {...rest} />
export const nav = ({...rest}) => <nav {...rest} />
export const noframes = ({...rest}) => <noframes {...rest} />
export const noscript = ({...rest}) => <noscript {...rest} />
export const object = ({children, ...rest}) => <object {...rest}>{children}</object>
export const ol = ({...rest}) => <ol {...rest} />
export const optgroup = ({...rest}) => <optgroup {...rest} />
export const option = ({...rest}) => <option {...rest} />
export const output = ({...rest}) => <output {...rest} />
export const p = ({...rest}) => <p {...rest} />
export const param = ({...rest}) => <param {...rest} />
export const picture = ({...rest}) => <picture {...rest} />
export const pre = ({...rest}) => <pre {...rest} />
export const progress = ({...rest}) => <progress {...rest} />
export const q = ({...rest}) => <q {...rest} />
export const rp = ({...rest}) => <rp {...rest} />
export const rt = ({...rest}) => <rt {...rest} />
export const ruby = ({...rest}) => <ruby {...rest} />
export const s = ({...rest}) => <s {...rest} />
export const samp = ({...rest}) => <samp {...rest} />
export const script = ({...rest}) => <script {...rest} />
export const section = ({...rest}) => <section {...rest} />
export const select = ({...rest}) => <select {...rest} />
export const small = ({...rest}) => <small {...rest} />
export const source = ({...rest}) => <source {...rest} />
export const span = ({...rest}) => <span {...rest} />
export const strike = ({...rest}) => <strike {...rest} />
export const strong = ({...rest}) => <strong {...rest} />
export const style = ({...rest}) => <style {...rest} />
export const sub = ({...rest}) => <sub {...rest} />
export const summary = ({...rest}) => <summary {...rest} />
export const sup = ({...rest}) => <sup {...rest} />
export const svg = ({...rest}) => <svg {...rest} />
export const table = ({...rest}) => <table {...rest} />
export const tbody = ({...rest}) => <tbody {...rest} />
export const td = ({...rest}) => <td {...rest} />
export const template = ({...rest}) => <template {...rest} />
export const textarea = ({...rest}) => <textarea {...rest} />
export const tfoot = ({...rest}) => <tfoot {...rest} />
export const th = ({...rest}) => <th {...rest} />
export const thead = ({...rest}) => <thead {...rest} />
export const time = ({...rest}) => <time {...rest} />
export const title = ({...rest}) => <title {...rest} />
export const tr = ({...rest}) => <tr {...rest} />
export const track = ({...rest}) => <track {...rest} />
export const tt = ({...rest}) => <tt {...rest} />
export const u = ({...rest}) => <u {...rest} />
export const ul = ({...rest}) => <ul {...rest} />
// export const var = ({...rest}) => <var {...rest} />
export const video = ({...rest}) => <video {...rest} />
export const wbr = ({...rest}) => <wbr {...rest} />